[package]
name = "g_shell"
version = "0.1.0"
authors = ["garebare <garedaiki@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = "0.19.0"
termion = "*"
whoami = "0.9.0"
dirs = "3.0"